### ISSUE TITLE
Release stable version

### ISSUE THREAD

**Issue by dennisdegreef** [piwi91/FormHandler#3]
To release a stable version, please use `git tag` and push it to github
- [x] Please choose a stable revision and navigate to there (if it's not HEAD)
  `git checkout $revision`
- [x] Tag the revision with a version number and annotation
  `git tag -a v1.0.0 -m 'Release v1.0.0'`
- [x] Push the tag to github to finalize it (if upstream is your remote, else use something like `origin`)
  `git push upstream v1.0.0`
- [x] Go to [packagist.org](packagist.org), log in, and press 'update'.

Composer should now be aware of a stable 1.0.0 release.
- [x] ...
- [x] Profit

**Comment by dennisdegreef** [comment]
@piwi91 After resolving mambo #5, do you think it's time to release a stable version? :)

**Comment by piwi91** [comment]
Stable version v1.0.0 released!
